/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    'node_modules/flowbite-react/lib/esm/**/*.js',
  ],
  theme: {
    extend: {
      spacing: {
        '128': '10rem',
        '1': '119rem',
        '4': '6rem',
        '2': '6rem',
        '222': '10.4rem',
        '3':'20rem',
        '7': '37.2rem',
        '6': '67rem',
        '66': '64rem',
        '55': '170rem',
        '75': '145rem',

      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
    fontWeight: {
      thin: '100',
      hairline: '100',
      extralight: '200',
      light: '300',
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      extrabold: '800',
      'extra-bold': '800',
      black: '900',
    },
    colors: {
      'transparent': 'transparent',
      'current': 'currentColor',
      'white': '#ffffff',
      'purple': '#3f3cbb',
      'midnight': '#121063',
      'metal': '#565584',
      'tahiti': '#3ab7bf',
      'silver': '#ecebff',
      'bubble-gum': '#ff77e9',
      'bermuda': '#78dcca',
      'items' : '#4D4D4D',
      'hero':'#F5F7FA',
      'greenLeaders':'#4CAF4F',
      'txt':'#4D4D4D',
      'pp':'#717171',
      'card':'#F5F7FA',
      'mail':'#212121',
      'ftr':'#263238',
    },
    fontFamily: {
      'sans': ['ui-sans-serif'], 'heroInter': ['Inter', 'sans'],
    },
    fontSize: {
      sm: '0.8rem',
      base: '1.1rem',
      xl: '1.25rem',
      '2xl': '1.563rem',
      '3xl': '1.953rem',
      '4xl': '2.441rem',
      '5xl': '3.052rem',
      '6xl':'3rem',
    },
    padding: {
      '88': '30rem',
      '77': '11rem',
      '33': '8rem',
      '22': '9rem',
      '23': '9rem',
      '1': '0.2rem',
      '4': '1rem',
      '2': '3rem',
      '11': '2rem',
      '3': '4rem',
      '5': '9rem',
    },
    margin: {
      '3': '0.7rem',
      '33': '8rem',
      '2': '3em',
      '4': '2em',
      '1': '1em'
    }

  },
  borderRadius: {
    'none': '0',
    'sm': '0.125rem',
    DEFAULT: '0.25rem',
    DEFAULT: '4px',
    'md': '0.375rem',
    'lg': '5rem',
    'llg': '0.5rem',
    'full': '9999px',
    'large': '12px',
  },
  plugins: [require('flowbite/plugin'),],
};
